const myScreenData = [
  {
    address: '서울시 종로구',
    name: '샤쿠란샤쿠란',
    score: 1,
  },
  {
    address: '서울시 강남구',
    name: '샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란샤쿠란',
    score: 5,
  },
  { address: '서울시 서초구', name: '샤쿠란', score: 3 },
  { address: '서울시 서초구', name: '샤쿠란', score: 4 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
  { address: '서울시 종로구', name: '팬케익', score: 2 },
];

export default myScreenData;
